AWSTemplateFormatVersion: 2010-09-09
Description: Cloudfront Parameter Example

Parameters:
  InstanceType:
    Description: Choose an EC2 instance type
    Type: String
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Default: t2.micro

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceType
      ImageId: ami-xxxxxxxxxxx